server:
  port:8201
spring:
  profiles: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZon: http://localhost:8000/eureka/
---
server:
  port:8202
spring:
  profiles: test
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZon: http://localhost:8000/eureka/